default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: blind_test_party_development

test:
  <<: *default
  database: blind_test_party_test

production:
  <<: *default
  database: blind_test_party_production
  username: blind_test_party
  password: <%= ENV['BLIND_TEST_PAERTY_DATABASE_PASSWORD'] %>
